In [2]:
import urllib.request

url = "https://raw.githubusercontent.com/karpathy/makemore/master/names.txt"

urllib.request.urlretrieve(url, "names.txt")

('names.txt', <http.client.HTTPMessage at 0x197e5627f10>)

In [3]:
words = open('names.txt' , 'r').read().splitlines()
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [4]:
len(words)

32033

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w in words)

15

In [7]:
# Exploring bigrams in the dataset
for w in words[:1]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1 , ch2 in zip(chs, chs[1:]):
        print(ch1 , ch2)

<S> e
e m
m m
m a
a <E>


In [8]:
for w in words[:3]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1 , ch2 in zip(chs, chs[1:]):
        print(ch1 , ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>
<S> a
a v
v a
a <E>


In [9]:
# counting bigrams in  python dictionary(to find out which character follows to other character)
b = {}
for w in words[:3]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1 , ch2 in zip(chs, chs[1:]):
        bigram = (ch1 , ch2)
        b[bigram] = b.get(bigram , 0) + 1
        print(ch1 , ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>
<S> a
a v
v a
a <E>


In [10]:
b

{('<S>', 'e'): 1,
 ('e', 'm'): 1,
 ('m', 'm'): 1,
 ('m', 'a'): 1,
 ('a', '<E>'): 3,
 ('<S>', 'o'): 1,
 ('o', 'l'): 1,
 ('l', 'i'): 1,
 ('i', 'v'): 1,
 ('v', 'i'): 1,
 ('i', 'a'): 1,
 ('<S>', 'a'): 1,
 ('a', 'v'): 1,
 ('v', 'a'): 1}

In [11]:
# counting bigrams in  python dictionary for entire file(to find out which character follows to other character)
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1 , ch2 in zip(chs, chs[1:]):
        bigram = (ch1 , ch2)
        b[bigram] = b.get(bigram , 0) + 1

In [12]:
b

{('<S>', 'e'): 1531,
 ('e', 'm'): 769,
 ('m', 'm'): 168,
 ('m', 'a'): 2590,
 ('a', '<E>'): 6640,
 ('<S>', 'o'): 394,
 ('o', 'l'): 619,
 ('l', 'i'): 2480,
 ('i', 'v'): 269,
 ('v', 'i'): 911,
 ('i', 'a'): 2445,
 ('<S>', 'a'): 4410,
 ('a', 'v'): 834,
 ('v', 'a'): 642,
 ('<S>', 'i'): 591,
 ('i', 's'): 1316,
 ('s', 'a'): 1201,
 ('a', 'b'): 541,
 ('b', 'e'): 655,
 ('e', 'l'): 3248,
 ('l', 'l'): 1345,
 ('l', 'a'): 2623,
 ('<S>', 's'): 2055,
 ('s', 'o'): 531,
 ('o', 'p'): 95,
 ('p', 'h'): 204,
 ('h', 'i'): 729,
 ('<S>', 'c'): 1542,
 ('c', 'h'): 664,
 ('h', 'a'): 2244,
 ('a', 'r'): 3264,
 ('r', 'l'): 413,
 ('l', 'o'): 692,
 ('o', 't'): 118,
 ('t', 't'): 374,
 ('t', 'e'): 716,
 ('e', '<E>'): 3983,
 ('<S>', 'm'): 2538,
 ('m', 'i'): 1256,
 ('a', 'm'): 1634,
 ('m', 'e'): 818,
 ('<S>', 'h'): 874,
 ('r', 'p'): 14,
 ('p', 'e'): 197,
 ('e', 'r'): 1958,
 ('r', '<E>'): 1377,
 ('e', 'v'): 463,
 ('v', 'e'): 568,
 ('l', 'y'): 1588,
 ('y', 'n'): 1826,
 ('n', '<E>'): 6763,
 ('b', 'i'): 217,
 ('i', 'g'): 428,


In [13]:
b.items()         # contains key, value pairs of tuple

dict_items([(('<S>', 'e'), 1531), (('e', 'm'), 769), (('m', 'm'), 168), (('m', 'a'), 2590), (('a', '<E>'), 6640), (('<S>', 'o'), 394), (('o', 'l'), 619), (('l', 'i'), 2480), (('i', 'v'), 269), (('v', 'i'), 911), (('i', 'a'), 2445), (('<S>', 'a'), 4410), (('a', 'v'), 834), (('v', 'a'), 642), (('<S>', 'i'), 591), (('i', 's'), 1316), (('s', 'a'), 1201), (('a', 'b'), 541), (('b', 'e'), 655), (('e', 'l'), 3248), (('l', 'l'), 1345), (('l', 'a'), 2623), (('<S>', 's'), 2055), (('s', 'o'), 531), (('o', 'p'), 95), (('p', 'h'), 204), (('h', 'i'), 729), (('<S>', 'c'), 1542), (('c', 'h'), 664), (('h', 'a'), 2244), (('a', 'r'), 3264), (('r', 'l'), 413), (('l', 'o'), 692), (('o', 't'), 118), (('t', 't'), 374), (('t', 'e'), 716), (('e', '<E>'), 3983), (('<S>', 'm'), 2538), (('m', 'i'), 1256), (('a', 'm'), 1634), (('m', 'e'), 818), (('<S>', 'h'), 874), (('r', 'p'), 14), (('p', 'e'), 197), (('e', 'r'), 1958), (('r', '<E>'), 1377), (('e', 'v'), 463), (('v', 'e'), 568), (('l', 'y'), 1588), (('y', 'n'), 18

In [14]:
sorted(b.items() , key = lambda kv : kv[1])   # print least common occurance

[(('q', 'r'), 1),
 (('d', 'z'), 1),
 (('p', 'j'), 1),
 (('q', 'l'), 1),
 (('p', 'f'), 1),
 (('q', 'e'), 1),
 (('b', 'c'), 1),
 (('c', 'd'), 1),
 (('m', 'f'), 1),
 (('p', 'n'), 1),
 (('w', 'b'), 1),
 (('p', 'c'), 1),
 (('h', 'p'), 1),
 (('f', 'h'), 1),
 (('b', 'j'), 1),
 (('f', 'g'), 1),
 (('z', 'g'), 1),
 (('c', 'p'), 1),
 (('p', 'k'), 1),
 (('p', 'm'), 1),
 (('x', 'n'), 1),
 (('s', 'q'), 1),
 (('k', 'f'), 1),
 (('m', 'k'), 1),
 (('x', 'h'), 1),
 (('g', 'f'), 1),
 (('v', 'b'), 1),
 (('j', 'p'), 1),
 (('g', 'z'), 1),
 (('v', 'd'), 1),
 (('d', 'b'), 1),
 (('v', 'h'), 1),
 (('h', 'h'), 1),
 (('g', 'v'), 1),
 (('d', 'q'), 1),
 (('x', 'b'), 1),
 (('w', 'z'), 1),
 (('h', 'q'), 1),
 (('j', 'b'), 1),
 (('x', 'm'), 1),
 (('w', 'g'), 1),
 (('t', 'b'), 1),
 (('z', 'x'), 1),
 (('p', 'b'), 2),
 (('t', 'g'), 2),
 (('q', 's'), 2),
 (('t', 'x'), 2),
 (('f', 'k'), 2),
 (('b', 't'), 2),
 (('j', 'n'), 2),
 (('k', 'c'), 2),
 (('z', 'k'), 2),
 (('s', 'j'), 2),
 (('s', 'f'), 2),
 (('z', 'j'), 2),
 (('n', 'q

In [15]:
sorted(b.items() , key = lambda kv : -kv[1])   # print most common occurance

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [16]:
import torch

In [17]:
# counting bigrams in 2D torch tensor array
a = torch.zeros((3,5) , dtype = torch.int32)

In [18]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [19]:
a[1,4] = 3

In [20]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 3],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [21]:
N = torch.zeros((28, 28) , dtype = torch.int32)

In [22]:
# we have to convert string (character) into integer as our array is int
chars = sorted(list(set(''.join(words))))      # list of all unique characters
# chars
stoi = {s:i for i , s in enumerate(chars)}
# stoi
stoi['<S>'] = 26
stoi['<E>'] = 27
stoi

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25,
 '<S>': 26,
 '<E>': 27}

In [23]:
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        N[row , col] += 1 

In [23]:
N

tensor([[ 556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568, 2528,
         1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,  182,
         2050,  435,    0, 6640],
        [ 321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,  103,
            0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,    0,
           83,    0,    0,  114],
        [ 815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,  116,
            0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,    3,
          104,    4,    0,   97],
        [1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,   60,
           30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,    0,
          317,    1,    0,  516],
        [ 679,  121,  153,  384, 1271,   82,  125,  152,  818,   55,  178, 3248,
          769, 2675,  269,   83,   14, 1958,  861,  580,   69,  463,   50,  132,
         1070,  181,    0, 3983],
        [ 242,    0,

In [ ]:
# the above result looks little ugly so make it more visual
import matplotlib.pyplot as plt
%matplotlib inline
plt.imshow(N)

In [24]:
itos = {i:s for s,i in stoi.items()}
itos

{0: 'a',
 1: 'b',
 2: 'c',
 3: 'd',
 4: 'e',
 5: 'f',
 6: 'g',
 7: 'h',
 8: 'i',
 9: 'j',
 10: 'k',
 11: 'l',
 12: 'm',
 13: 'n',
 14: 'o',
 15: 'p',
 16: 'q',
 17: 'r',
 18: 's',
 19: 't',
 20: 'u',
 21: 'v',
 22: 'w',
 23: 'x',
 24: 'y',
 25: 'z',
 26: '<S>',
 27: '<E>'}

In [ ]:
# the above result still looks little ugly so make it more visual
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize = (16,16))
plt.imshow(N , cmap = "Blues")

for i in range(28):
    for j in range(28):
        chstr = itos[i] + itos[j]
        plt.text(j , i , chstr, ha="center" , va="bottom" , color="gray")
        plt.text(j , i, N[i , j].item(), ha="center" , va="top" , color="gray")
plt.axis("off");


In [25]:
# as in the above figure you can see that <E>a to <E><E> is always Zero as <E> is never going to be first character of bigram
# same as a<S> to <S><E> is always zero as <S> is never going to be last character of bigram 
# so deleting spurious <S> , <E> tokens in a favors of a single "." token
N = torch.zeros((27, 27) , dtype = torch.int32)

In [26]:
# we have to convert string (character) into integer as our array is int
chars = sorted(list(set(''.join(words))))      # list of all unique characters
# chars
stoi = {s:i+1 for i , s in enumerate(chars)}
# stoi
stoi['.'] = 0
stoi
itos = {i:s for s,i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [27]:
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        N[row , col] += 1 

In [ ]:
# the above result still looks little ugly so make it more visual
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize = (16,16))
plt.imshow(N , cmap = "Blues")

for i in range(27):
    for j in range(27):
        chstr = itos[i] + itos[j]
        plt.text(j , i , chstr, ha="center" , va="bottom" , color="gray")
        plt.text(j , i, N[i , j].item(), ha="center" , va="top" , color="gray")
plt.axis("off");


In [28]:
# samplling from the model (create some names from the model) for that we will use generator and multinomial
# N[0,:]
N[0]
N[0].shape

torch.Size([27])

In [29]:
# for multinomial we have to know probability so for that
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [30]:
# generator
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3 , generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [31]:
# multinomial
torch.multinomial(p , num_samples = 20 , replacement=True , generator = g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [32]:
# let's find out first character for the sample
g = torch.Generator().manual_seed(2147483647)
index = torch.multinomial(p , num_samples = 1 , replacement = True , generator = g).item()
itos[index]

'.'

In [33]:
# now let's create list of names
g = torch.Generator().manual_seed(2147483647)

for i in range(20):
    out = []
    ix = 0
    while True:
        p = N[ix].float()
        p = p / p.sum()
        ix = torch.multinomial(p , num_samples = 1 , replacement = True , generator = g).item()
        out.append(itos[ix])
        if(ix == 0):
            break
    print(''.join(out)) 

cexze.
momasurailezitynn.
konimittain.
llayn.
ka.
da.
staiyaubrtthrigotai.
moliellavo.
ke.
teda.
ka.
emimmsade.
enkaviyny.
ftlspihinivenvorhlasu.
dsor.
br.
jol.
pen.
aisan.
ja.


In [34]:
P = N.float()
P = P.sum(1, keepdim = True).shape
P

# 27 , 27 which is N
# 27 , 1  which is P both are broadcastable

torch.Size([27, 1])

In [35]:
P = N.float()
P = P.sum(1).shape
P

# 27 , 27 which is N
# 27   which is P both are broadcastable as now P becomes 1 ,27 but it can change the result

torch.Size([27])

In [36]:
# Efficiency : vectorized normalization of rows (broadcasting)
# what we are doing here is we are always fetching row of N from the counnt matrix , converting into float and dividing ans we are doing this again and again for every iteration
# it is extremely inefficient and wasteful  [p = N[ix].float();  p = p / p.sum()]
P = N.float()
P = P / P.sum(1, keepdim = True)

In [37]:
# now let's create list of names with more efficiency
g = torch.Generator().manual_seed(2147483647)

for i in range(20):
    out = []
    ix = 0
    while True:
        p = P[ix]
        ix = torch.multinomial(p , num_samples = 1 , replacement = True , generator = g).item()
        out.append(itos[ix])
        if(ix == 0):
            break
    print(''.join(out)) 

cexze.
momasurailezitynn.
konimittain.
llayn.
ka.
da.
staiyaubrtthrigotai.
moliellavo.
ke.
teda.
ka.
emimmsade.
enkaviyny.
ftlspihinivenvorhlasu.
dsor.
br.
jol.
pen.
aisan.
ja.


In [38]:
# GOAL : Maximize likelihood of data with respect to model parameters 
# equivalent to maximize the log likelihood (beacuse log is monotonic)
# equivalent to minimize the negative log likelihood
# equivalent to minimize the average negative log likelihood 

# log(a*b*c) = log(a) + log(b) + log(c)

In [39]:
# Quality of the model (loss function = average negative log likelihood )
# (loss function is lower, better quality of model)

log_likelihood = 0.0
n = 0

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        prob = P[row , col]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
#         print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print('---')
print(f'{log_likelihood=})')
negate_log_likelihood = -log_likelihood
print(f'{negate_log_likelihood=}')
print(f'{negate_log_likelihood/n}')

---
log_likelihood=tensor(-559891.7500))
negate_log_likelihood=tensor(559891.7500)
2.454094171524048


In [40]:
log_likelihood = 0.0
n = 0

for w in ["krupa"]:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        prob = P[row , col]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print('---')
print(f'{log_likelihood=})')
negate_log_likelihood = -log_likelihood
print(f'{negate_log_likelihood=}')
print(f'{negate_log_likelihood/n}')

.k: 0.0925 -2.3806
kr: 0.0216 -3.8338
ru: 0.0198 -3.9199
up: 0.0051 -5.2778
pa: 0.2037 -1.5911
a.: 0.1960 -1.6299
---
log_likelihood=tensor(-18.6331))
negate_log_likelihood=tensor(18.6331)
3.10550856590271


In [41]:
log_likelihood = 0.0
n = 0

for w in ["krupjq"]:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        prob = P[row , col]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print('---')
print(f'{log_likelihood=})')
negate_log_likelihood = -log_likelihood
print(f'{negate_log_likelihood=}')
print(f'{negate_log_likelihood/n}')

.k: 0.0925 -2.3806
kr: 0.0216 -3.8338
ru: 0.0198 -3.9199
up: 0.0051 -5.2778
pj: 0.0010 -6.9334
jq: 0.0000 -inf
q.: 0.1029 -2.2736
---
log_likelihood=tensor(-inf))
negate_log_likelihood=tensor(inf)
inf


In [42]:
# in the above example you can see loss is infinity as j and q has 0 probability
# to make the model smoother, we can add fake counts so that loss is not going to be infinity
P = (N+1).float()
P /= P.sum(1 , keepdim = True)

In [44]:
# now you can see loss is not infinity because j and q has very small probability
log_likelihood = 0.0
n = 0

for w in ["krupjq"]:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        prob = P[row , col]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print('---')
print(f'{log_likelihood=})')
negate_log_likelihood = -log_likelihood
print(f'{negate_log_likelihood=}')
print(f'{negate_log_likelihood/n}')

.k: 0.0925 -2.3811
kr: 0.0217 -3.8300
ru: 0.0199 -3.9181
up: 0.0054 -5.2257
pj: 0.0019 -6.2663
jq: 0.0003 -7.9817
q.: 0.0970 -2.3331
---
log_likelihood=tensor(-31.9361))
negate_log_likelihood=tensor(31.9361)
4.5622944831848145
