In [1]:
# now we would like to take an alternative approach. We will end up in a very similar position but with neural network framework.


In [1]:
import urllib.request
import torch
url = "https://raw.githubusercontent.com/karpathy/makemore/master/names.txt"

urllib.request.urlretrieve(url, "names.txt")

('names.txt', <http.client.HTTPMessage at 0x15f3dcf7cd0>)

In [2]:
words = open('names.txt' , 'r').read().splitlines()
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
chars = sorted(list(set(''.join(words))))      # list of all unique characters
# chars
stoi = {s:i+1 for i , s in enumerate(chars)}
# stoi
stoi['.'] = 0
stoi
itos = {i:s for s,i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [4]:
# creating set of bigram of training model (x = input , y = target)
xs , ys = [] , []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
        print(ch1 , ch2)
        xs.append(row)
        ys.append(col)

xs = torch.tensor(xs)
ys = torch.tensor(ys)   

. e
e m
m m
m a
a .


In [5]:
xs

tensor([ 0,  5, 13, 13,  1])

In [6]:
ys

tensor([ 5, 13, 13,  1,  0])

In [7]:
# we can not feeding this integer to the neural network so we create float vector of this integer
# for that we will use One Hot Encoding function
import torch.nn.functional as F
x_encode = F.one_hot(xs , num_classes = 27).float()
x_encode

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.imshow(x_encode)

In [8]:
x_encode.dtype

torch.float32

In [9]:
# The Neural network : one linear layer of neurons implemented with matrix multiplication
W = torch.randn(27,1)
x_encode @ W     # input * weights

tensor([[-0.1034],
        [-0.1743],
        [ 1.6082],
        [ 1.6082],
        [-0.4286]])

In [10]:
W      # only for one neuron

tensor([[-0.1034],
        [-0.4286],
        [ 0.4567],
        [ 0.6562],
        [-1.0206],
        [-0.1743],
        [-0.4943],
        [ 0.3770],
        [ 1.5931],
        [-1.1234],
        [ 1.5861],
        [ 1.3215],
        [ 0.2726],
        [ 1.6082],
        [ 0.3566],
        [ 1.8123],
        [ 0.6036],
        [ 0.0174],
        [ 0.0236],
        [-0.1422],
        [-0.0666],
        [ 0.4046],
        [ 0.5523],
        [ 0.9734],
        [-1.6416],
        [ 0.5786],
        [-0.3945]])

In [11]:
# for multiple neurons (randomly initializes 27 neuron's weights, each neuron receives 27 inputs)
g = torch.Generator().manual_seed(2147483647)
W = torch.randn(27 ,27 , generator = g)
x_encode @ W

tensor([[ 1.5674e+00, -2.3729e-01, -2.7385e-02, -1.1008e+00,  2.8588e-01,
         -2.9643e-02, -1.5471e+00,  6.0489e-01,  7.9136e-02,  9.0462e-01,
         -4.7125e-01,  7.8682e-01, -3.2843e-01, -4.3297e-01,  1.3729e+00,
          2.9334e+00,  1.5618e+00, -1.6261e+00,  6.7716e-01, -8.4039e-01,
          9.8488e-01, -1.4837e-01, -1.4795e+00,  4.4830e-01, -7.0730e-02,
          2.4968e+00,  2.4448e+00],
        [ 4.7236e-01,  1.4830e+00,  3.1748e-01,  1.0588e+00,  2.3982e+00,
          4.6827e-01, -6.5650e-01,  6.1662e-01, -6.2197e-01,  5.1007e-01,
          1.3563e+00,  2.3445e-01, -4.5585e-01, -1.3132e-03, -5.1161e-01,
          5.5570e-01,  4.7458e-01, -1.3867e+00,  1.6229e+00,  1.7197e-01,
          9.8846e-01,  5.0657e-01,  1.0198e+00, -1.9062e+00, -4.2753e-01,
         -2.1259e+00,  9.6041e-01],
        [ 1.9359e-01,  1.0532e+00,  6.3393e-01,  2.5786e-01,  9.6408e-01,
         -2.4855e-01,  2.4756e-02, -3.0404e-02,  1.5622e+00, -4.4852e-01,
         -1.2345e+00,  1.1220e+00, -6.73

In [12]:
# (5 , 27) @ (27 , 27)  = (5 ,27) which means 5 inputs and 27 output of neuron which are input for next layer

In [13]:
# for evaluate count matrix we have to find exponent of all these (5 ,27) 
logits = x_encode @ W
counts = logits.exp()        #equivalent to N
counts

tensor([[ 4.7940,  0.7888,  0.9730,  0.3326,  1.3309,  0.9708,  0.2129,  1.8311,
          1.0824,  2.4710,  0.6242,  2.1964,  0.7200,  0.6486,  3.9469, 18.7908,
          4.7673,  0.1967,  1.9683,  0.4315,  2.6775,  0.8621,  0.2277,  1.5656,
          0.9317, 12.1434, 11.5281],
        [ 1.6038,  4.4060,  1.3737,  2.8830, 11.0032,  1.5972,  0.5187,  1.8527,
          0.5369,  1.6654,  3.8818,  1.2642,  0.6339,  0.9987,  0.5995,  1.7432,
          1.6073,  0.2499,  5.0680,  1.1876,  2.6871,  1.6596,  2.7728,  0.1486,
          0.6521,  0.1193,  2.6128],
        [ 1.2136,  2.8669,  1.8850,  1.2942,  2.6224,  0.7799,  1.0251,  0.9701,
          4.7691,  0.6386,  0.2910,  3.0710,  0.5098,  1.0386,  0.5719,  0.4373,
          2.2763,  0.4719,  2.5289,  0.2265,  0.8082,  0.3054,  0.5164,  0.7918,
          4.6866,  1.8232,  0.4921],
        [ 1.2136,  2.8669,  1.8850,  1.2942,  2.6224,  0.7799,  1.0251,  0.9701,
          4.7691,  0.6386,  0.2910,  3.0710,  0.5098,  1.0386,  0.5719,  0.4373

In [14]:
# transforming neural nets output into probabilities (softmax)
probs = counts / counts.sum(1 , keepdim = True)
probs     # probabilities for the next character

tensor([[0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
         0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
         0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459],
        [0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
         0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
         0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472],
        [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
         0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
         0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
        [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
         0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
         0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
        [0.0150, 0.0086,

In [15]:
# find out loss function as average negative log likelihood
nlls = torch.zeros(5)
for i in range(5):
    x = xs[i].item();    # input character index
    y = ys[i].item();    # output(label) character index
    print('-------')
    print(f'Bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x}{y})')
    print(f'input to the neural network:', x)
    print(f'output probabilities from the neural network:', probs[i])
    print(f'label (actual next character):', y)
    p = probs[i , y]
    print(f'probabilites assigned by the network to the correct character:', p.item())
    logp = torch.log(p)
    print(f'log likelihood:' , logp.item())
    nll = -logp
    print(f'negative log likelihood:', nll.item())
    nlls[i] = nll
    
print('=======')
print(f'Average negative log likelihood i.e. loss =', nlls.mean().item())

-------
Bigram example 1: .e (indexes 05)
input to the neural network: 0
output probabilities from the neural network: tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
label (actual next character): 5
probabilites assigned by the network to the correct character: 0.01228625513613224
log likelihood: -4.399273872375488
negative log likelihood: 4.399273872375488
-------
Bigram example 2: em (indexes 513)
input to the neural network: 5
output probabilities from the neural network: tensor([0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
        0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
        0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472])
label (actual next character): 13
probabilites assigned by the network to the correct

In [16]:
# Decreasing loss by doing iteration of forward pass , backward pass and update

g = torch.Generator().manual_seed(2147483647)
W = torch.randn(27 ,27 , generator = g , requires_grad = True)

for k in range(10):

    # forward pass
    x_encode = F.one_hot(xs , num_classes = 27).float()
    logits = x_encode @ W
    counts = logits.exp()        #equivalent to N
    probs = counts / counts.sum(1 , keepdim = True)
    loss = -probs[torch.arange(5) , ys].log().mean()
    print(loss.item())
    
    # backward pass
    W.grad = None
    loss.backward()
    
    # update
    W.data += -0.1 * W.grad


3.7693049907684326
3.7492127418518066
3.7291626930236816
3.7091541290283203
3.6891887187957764
3.6692662239074707
3.6493873596191406
3.629552125930786
3.6097614765167236
3.5900158882141113


In [26]:
# Putting everything together
# creating set of bigram of training model (x = input , y = target)
xs , ys = [] , []
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs, chs[1:]):
        row = stoi[ch1]
        col = stoi[ch2]
#         print(ch1 , ch2)
        xs.append(row)
        ys.append(col)
xs = torch.tensor(xs)
ys = torch.tensor(ys)  
number = xs.nelement()
print('-----')
print(f'number of examples : ', number)
print('-----')
# Decreasing loss by doing iteration of forward pass , backward pass and update

g = torch.Generator().manual_seed(2147483647)
W = torch.randn(27 ,27 , generator = g , requires_grad = True)

for k in range(100):

    # forward pass
    x_encode = F.one_hot(xs , num_classes = 27).float()
    logits = x_encode @ W
    counts = logits.exp()        #equivalent to N
    probs = counts / counts.sum(1 , keepdim = True)
    loss = -probs[torch.arange(number) , ys].log().mean()
    print(loss.item())
    
    # backward pass
    W.grad = None
    loss.backward()
    
    # update
    W.data += -50 * W.grad


-----
number of examples :  228146
-----
3.758953809738159
3.371100902557373
3.154043197631836
3.020373821258545
2.927711248397827
2.8604023456573486
2.8097293376922607
2.7701022624969482
2.7380728721618652
2.711496353149414
2.6890029907226562
2.6696884632110596
2.6529300212860107
2.638277769088745
2.6253879070281982
2.6139907836914062
2.60386323928833
2.5948219299316406
2.5867116451263428
2.5794036388397217
2.572789192199707
2.5667762756347656
2.5612878799438477
2.5562589168548584
2.551633596420288
2.547366142272949
2.5434155464172363
2.539748430252075
2.5363364219665527
2.5331544876098633
2.5301806926727295
2.5273969173431396
2.5247862339019775
2.522334575653076
2.520029067993164
2.517857789993286
2.515810966491699
2.513878345489502
2.512052059173584
2.5103237628936768
2.5086867809295654
2.5071346759796143
2.5056610107421875
2.504261016845703
2.502929210662842
2.5016608238220215
2.5004520416259766
2.4992988109588623
2.498197317123413
2.497144937515259
2.496137857437134
2.495173692703